DROP TABLE IF EXISTS airport;
CREATE TABLE airport( 
IATA_CODE TEXT,
AIRPORT	TEXT,
CITY TEXT,
STATE TEXT,
COUNTRY TEXT,	
LATITUDE DOUBLE PRECISION,
LONGITUDE DOUBLE PRW
);
COPY airport
FROM 'D:/Aviation DA/airports.csv'
DELIMITER ','
CSV HEADER;

